// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf-examples/vs-prost/src/triangle.proto

public final class TriangleOuterClass {
  private TriangleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Color}
   */
  public enum Color
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>RED = 1;</code>
     */
    RED(1),
    /**
     * <code>GREEN = 2;</code>
     */
    GREEN(2),
    /**
     * <code>BLUE = 3;</code>
     */
    BLUE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>RED = 1;</code>
     */
    public static final int RED_VALUE = 1;
    /**
     * <code>GREEN = 2;</code>
     */
    public static final int GREEN_VALUE = 2;
    /**
     * <code>BLUE = 3;</code>
     */
    public static final int BLUE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Color valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Color forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return RED;
        case 2: return GREEN;
        case 3: return BLUE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Color>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Color> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Color>() {
            public Color findValueByNumber(int number) {
              return Color.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return TriangleOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Color[] VALUES = values();

    public static Color valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Color(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Color)
  }

  public interface PropertiesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Properties)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 p1 = 1;</code>
     * @return The p1.
     */
    int getP1();

    /**
     * <code>string p2 = 2;</code>
     * @return The p2.
     */
    java.lang.String getP2();
    /**
     * <code>string p2 = 2;</code>
     * @return The bytes for p2.
     */
    com.google.protobuf.ByteString
        getP2Bytes();

    public TriangleOuterClass.Properties.PropertiesCase getPropertiesCase();
  }
  /**
   * Protobuf type {@code Properties}
   */
  public static final class Properties extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Properties)
      PropertiesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Properties.newBuilder() to construct.
    private Properties(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Properties() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Properties();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Properties(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              propertiesCase_ = 1;
              properties_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              propertiesCase_ = 2;
              properties_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TriangleOuterClass.internal_static_Properties_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TriangleOuterClass.internal_static_Properties_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TriangleOuterClass.Properties.class, TriangleOuterClass.Properties.Builder.class);
    }

    private int propertiesCase_ = 0;
    private java.lang.Object properties_;
    public enum PropertiesCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      P1(1),
      P2(2),
      PROPERTIES_NOT_SET(0);
      private final int value;
      private PropertiesCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PropertiesCase valueOf(int value) {
        return forNumber(value);
      }

      public static PropertiesCase forNumber(int value) {
        switch (value) {
          case 1: return P1;
          case 2: return P2;
          case 0: return PROPERTIES_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PropertiesCase
    getPropertiesCase() {
      return PropertiesCase.forNumber(
          propertiesCase_);
    }

    public static final int P1_FIELD_NUMBER = 1;
    /**
     * <code>int32 p1 = 1;</code>
     * @return The p1.
     */
    @java.lang.Override
    public int getP1() {
      if (propertiesCase_ == 1) {
        return (java.lang.Integer) properties_;
      }
      return 0;
    }

    public static final int P2_FIELD_NUMBER = 2;
    /**
     * <code>string p2 = 2;</code>
     * @return The p2.
     */
    public java.lang.String getP2() {
      java.lang.Object ref = "";
      if (propertiesCase_ == 2) {
        ref = properties_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (propertiesCase_ == 2) {
          properties_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string p2 = 2;</code>
     * @return The bytes for p2.
     */
    public com.google.protobuf.ByteString
        getP2Bytes() {
      java.lang.Object ref = "";
      if (propertiesCase_ == 2) {
        ref = properties_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (propertiesCase_ == 2) {
          properties_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (propertiesCase_ == 1) {
        output.writeInt32(
            1, (int)((java.lang.Integer) properties_));
      }
      if (propertiesCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, properties_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (propertiesCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              1, (int)((java.lang.Integer) properties_));
      }
      if (propertiesCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, properties_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TriangleOuterClass.Properties)) {
        return super.equals(obj);
      }
      TriangleOuterClass.Properties other = (TriangleOuterClass.Properties) obj;

      if (!getPropertiesCase().equals(other.getPropertiesCase())) return false;
      switch (propertiesCase_) {
        case 1:
          if (getP1()
              != other.getP1()) return false;
          break;
        case 2:
          if (!getP2()
              .equals(other.getP2())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (propertiesCase_) {
        case 1:
          hash = (37 * hash) + P1_FIELD_NUMBER;
          hash = (53 * hash) + getP1();
          break;
        case 2:
          hash = (37 * hash) + P2_FIELD_NUMBER;
          hash = (53 * hash) + getP2().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TriangleOuterClass.Properties parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TriangleOuterClass.Properties parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TriangleOuterClass.Properties parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TriangleOuterClass.Properties parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TriangleOuterClass.Properties parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TriangleOuterClass.Properties parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TriangleOuterClass.Properties parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TriangleOuterClass.Properties parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TriangleOuterClass.Properties parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TriangleOuterClass.Properties parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TriangleOuterClass.Properties parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TriangleOuterClass.Properties parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TriangleOuterClass.Properties prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Properties}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Properties)
        TriangleOuterClass.PropertiesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TriangleOuterClass.internal_static_Properties_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TriangleOuterClass.internal_static_Properties_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TriangleOuterClass.Properties.class, TriangleOuterClass.Properties.Builder.class);
      }

      // Construct using TriangleOuterClass.Properties.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        propertiesCase_ = 0;
        properties_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TriangleOuterClass.internal_static_Properties_descriptor;
      }

      @java.lang.Override
      public TriangleOuterClass.Properties getDefaultInstanceForType() {
        return TriangleOuterClass.Properties.getDefaultInstance();
      }

      @java.lang.Override
      public TriangleOuterClass.Properties build() {
        TriangleOuterClass.Properties result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TriangleOuterClass.Properties buildPartial() {
        TriangleOuterClass.Properties result = new TriangleOuterClass.Properties(this);
        if (propertiesCase_ == 1) {
          result.properties_ = properties_;
        }
        if (propertiesCase_ == 2) {
          result.properties_ = properties_;
        }
        result.propertiesCase_ = propertiesCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TriangleOuterClass.Properties) {
          return mergeFrom((TriangleOuterClass.Properties)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TriangleOuterClass.Properties other) {
        if (other == TriangleOuterClass.Properties.getDefaultInstance()) return this;
        switch (other.getPropertiesCase()) {
          case P1: {
            setP1(other.getP1());
            break;
          }
          case P2: {
            propertiesCase_ = 2;
            properties_ = other.properties_;
            onChanged();
            break;
          }
          case PROPERTIES_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TriangleOuterClass.Properties parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TriangleOuterClass.Properties) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int propertiesCase_ = 0;
      private java.lang.Object properties_;
      public PropertiesCase
          getPropertiesCase() {
        return PropertiesCase.forNumber(
            propertiesCase_);
      }

      public Builder clearProperties() {
        propertiesCase_ = 0;
        properties_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>int32 p1 = 1;</code>
       * @return The p1.
       */
      public int getP1() {
        if (propertiesCase_ == 1) {
          return (java.lang.Integer) properties_;
        }
        return 0;
      }
      /**
       * <code>int32 p1 = 1;</code>
       * @param value The p1 to set.
       * @return This builder for chaining.
       */
      public Builder setP1(int value) {
        propertiesCase_ = 1;
        properties_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 p1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearP1() {
        if (propertiesCase_ == 1) {
          propertiesCase_ = 0;
          properties_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string p2 = 2;</code>
       * @return The p2.
       */
      @java.lang.Override
      public java.lang.String getP2() {
        java.lang.Object ref = "";
        if (propertiesCase_ == 2) {
          ref = properties_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (propertiesCase_ == 2) {
            properties_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string p2 = 2;</code>
       * @return The bytes for p2.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getP2Bytes() {
        java.lang.Object ref = "";
        if (propertiesCase_ == 2) {
          ref = properties_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (propertiesCase_ == 2) {
            properties_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string p2 = 2;</code>
       * @param value The p2 to set.
       * @return This builder for chaining.
       */
      public Builder setP2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  propertiesCase_ = 2;
        properties_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string p2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearP2() {
        if (propertiesCase_ == 2) {
          propertiesCase_ = 0;
          properties_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string p2 = 2;</code>
       * @param value The bytes for p2 to set.
       * @return This builder for chaining.
       */
      public Builder setP2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        propertiesCase_ = 2;
        properties_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Properties)
    }

    // @@protoc_insertion_point(class_scope:Properties)
    private static final TriangleOuterClass.Properties DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TriangleOuterClass.Properties();
    }

    public static TriangleOuterClass.Properties getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Properties>
        PARSER = new com.google.protobuf.AbstractParser<Properties>() {
      @java.lang.Override
      public Properties parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Properties(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Properties> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Properties> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TriangleOuterClass.Properties getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TriangleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Triangle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string description = 1;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 1;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>.Color color = 2;</code>
     * @return The enum numeric value on the wire for color.
     */
    int getColorValue();
    /**
     * <code>.Color color = 2;</code>
     * @return The color.
     */
    TriangleOuterClass.Color getColor();

    /**
     * <code>.Properties properties = 3;</code>
     * @return Whether the properties field is set.
     */
    boolean hasProperties();
    /**
     * <code>.Properties properties = 3;</code>
     * @return The properties.
     */
    TriangleOuterClass.Properties getProperties();
    /**
     * <code>.Properties properties = 3;</code>
     */
    TriangleOuterClass.PropertiesOrBuilder getPropertiesOrBuilder();

    /**
     * <code>int32 struct = 4;</code>
     * @return The struct.
     */
    int getStruct();
  }
  /**
   * Protobuf type {@code Triangle}
   */
  public static final class Triangle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Triangle)
      TriangleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Triangle.newBuilder() to construct.
    private Triangle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Triangle() {
      description_ = "";
      color_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Triangle();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Triangle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              color_ = rawValue;
              break;
            }
            case 26: {
              TriangleOuterClass.Properties.Builder subBuilder = null;
              if (properties_ != null) {
                subBuilder = properties_.toBuilder();
              }
              properties_ = input.readMessage(TriangleOuterClass.Properties.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(properties_);
                properties_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              struct_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TriangleOuterClass.internal_static_Triangle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TriangleOuterClass.internal_static_Triangle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TriangleOuterClass.Triangle.class, TriangleOuterClass.Triangle.Builder.class);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 1;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 1;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private int color_;
    /**
     * <code>.Color color = 2;</code>
     * @return The enum numeric value on the wire for color.
     */
    @java.lang.Override public int getColorValue() {
      return color_;
    }
    /**
     * <code>.Color color = 2;</code>
     * @return The color.
     */
    @java.lang.Override public TriangleOuterClass.Color getColor() {
      @SuppressWarnings("deprecation")
      TriangleOuterClass.Color result = TriangleOuterClass.Color.valueOf(color_);
      return result == null ? TriangleOuterClass.Color.UNRECOGNIZED : result;
    }

    public static final int PROPERTIES_FIELD_NUMBER = 3;
    private TriangleOuterClass.Properties properties_;
    /**
     * <code>.Properties properties = 3;</code>
     * @return Whether the properties field is set.
     */
    @java.lang.Override
    public boolean hasProperties() {
      return properties_ != null;
    }
    /**
     * <code>.Properties properties = 3;</code>
     * @return The properties.
     */
    @java.lang.Override
    public TriangleOuterClass.Properties getProperties() {
      return properties_ == null ? TriangleOuterClass.Properties.getDefaultInstance() : properties_;
    }
    /**
     * <code>.Properties properties = 3;</code>
     */
    @java.lang.Override
    public TriangleOuterClass.PropertiesOrBuilder getPropertiesOrBuilder() {
      return getProperties();
    }

    public static final int STRUCT_FIELD_NUMBER = 4;
    private int struct_;
    /**
     * <code>int32 struct = 4;</code>
     * @return The struct.
     */
    @java.lang.Override
    public int getStruct() {
      return struct_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, description_);
      }
      if (color_ != TriangleOuterClass.Color.UNKNOWN.getNumber()) {
        output.writeEnum(2, color_);
      }
      if (properties_ != null) {
        output.writeMessage(3, getProperties());
      }
      if (struct_ != 0) {
        output.writeInt32(4, struct_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, description_);
      }
      if (color_ != TriangleOuterClass.Color.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, color_);
      }
      if (properties_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getProperties());
      }
      if (struct_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, struct_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TriangleOuterClass.Triangle)) {
        return super.equals(obj);
      }
      TriangleOuterClass.Triangle other = (TriangleOuterClass.Triangle) obj;

      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (color_ != other.color_) return false;
      if (hasProperties() != other.hasProperties()) return false;
      if (hasProperties()) {
        if (!getProperties()
            .equals(other.getProperties())) return false;
      }
      if (getStruct()
          != other.getStruct()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + color_;
      if (hasProperties()) {
        hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + getProperties().hashCode();
      }
      hash = (37 * hash) + STRUCT_FIELD_NUMBER;
      hash = (53 * hash) + getStruct();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TriangleOuterClass.Triangle parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TriangleOuterClass.Triangle parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TriangleOuterClass.Triangle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TriangleOuterClass.Triangle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TriangleOuterClass.Triangle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TriangleOuterClass.Triangle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TriangleOuterClass.Triangle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TriangleOuterClass.Triangle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TriangleOuterClass.Triangle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TriangleOuterClass.Triangle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TriangleOuterClass.Triangle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TriangleOuterClass.Triangle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TriangleOuterClass.Triangle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Triangle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Triangle)
        TriangleOuterClass.TriangleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TriangleOuterClass.internal_static_Triangle_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TriangleOuterClass.internal_static_Triangle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TriangleOuterClass.Triangle.class, TriangleOuterClass.Triangle.Builder.class);
      }

      // Construct using TriangleOuterClass.Triangle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        description_ = "";

        color_ = 0;

        if (propertiesBuilder_ == null) {
          properties_ = null;
        } else {
          properties_ = null;
          propertiesBuilder_ = null;
        }
        struct_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TriangleOuterClass.internal_static_Triangle_descriptor;
      }

      @java.lang.Override
      public TriangleOuterClass.Triangle getDefaultInstanceForType() {
        return TriangleOuterClass.Triangle.getDefaultInstance();
      }

      @java.lang.Override
      public TriangleOuterClass.Triangle build() {
        TriangleOuterClass.Triangle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TriangleOuterClass.Triangle buildPartial() {
        TriangleOuterClass.Triangle result = new TriangleOuterClass.Triangle(this);
        result.description_ = description_;
        result.color_ = color_;
        if (propertiesBuilder_ == null) {
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        result.struct_ = struct_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TriangleOuterClass.Triangle) {
          return mergeFrom((TriangleOuterClass.Triangle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TriangleOuterClass.Triangle other) {
        if (other == TriangleOuterClass.Triangle.getDefaultInstance()) return this;
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.color_ != 0) {
          setColorValue(other.getColorValue());
        }
        if (other.hasProperties()) {
          mergeProperties(other.getProperties());
        }
        if (other.getStruct() != 0) {
          setStruct(other.getStruct());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TriangleOuterClass.Triangle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TriangleOuterClass.Triangle) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 1;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 1;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 1;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 1;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int color_ = 0;
      /**
       * <code>.Color color = 2;</code>
       * @return The enum numeric value on the wire for color.
       */
      @java.lang.Override public int getColorValue() {
        return color_;
      }
      /**
       * <code>.Color color = 2;</code>
       * @param value The enum numeric value on the wire for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorValue(int value) {
        
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Color color = 2;</code>
       * @return The color.
       */
      @java.lang.Override
      public TriangleOuterClass.Color getColor() {
        @SuppressWarnings("deprecation")
        TriangleOuterClass.Color result = TriangleOuterClass.Color.valueOf(color_);
        return result == null ? TriangleOuterClass.Color.UNRECOGNIZED : result;
      }
      /**
       * <code>.Color color = 2;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(TriangleOuterClass.Color value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        color_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Color color = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        
        color_ = 0;
        onChanged();
        return this;
      }

      private TriangleOuterClass.Properties properties_;
      private com.google.protobuf.SingleFieldBuilderV3<
          TriangleOuterClass.Properties, TriangleOuterClass.Properties.Builder, TriangleOuterClass.PropertiesOrBuilder> propertiesBuilder_;
      /**
       * <code>.Properties properties = 3;</code>
       * @return Whether the properties field is set.
       */
      public boolean hasProperties() {
        return propertiesBuilder_ != null || properties_ != null;
      }
      /**
       * <code>.Properties properties = 3;</code>
       * @return The properties.
       */
      public TriangleOuterClass.Properties getProperties() {
        if (propertiesBuilder_ == null) {
          return properties_ == null ? TriangleOuterClass.Properties.getDefaultInstance() : properties_;
        } else {
          return propertiesBuilder_.getMessage();
        }
      }
      /**
       * <code>.Properties properties = 3;</code>
       */
      public Builder setProperties(TriangleOuterClass.Properties value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          properties_ = value;
          onChanged();
        } else {
          propertiesBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Properties properties = 3;</code>
       */
      public Builder setProperties(
          TriangleOuterClass.Properties.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          properties_ = builderForValue.build();
          onChanged();
        } else {
          propertiesBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Properties properties = 3;</code>
       */
      public Builder mergeProperties(TriangleOuterClass.Properties value) {
        if (propertiesBuilder_ == null) {
          if (properties_ != null) {
            properties_ =
              TriangleOuterClass.Properties.newBuilder(properties_).mergeFrom(value).buildPartial();
          } else {
            properties_ = value;
          }
          onChanged();
        } else {
          propertiesBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Properties properties = 3;</code>
       */
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = null;
          onChanged();
        } else {
          properties_ = null;
          propertiesBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Properties properties = 3;</code>
       */
      public TriangleOuterClass.Properties.Builder getPropertiesBuilder() {
        
        onChanged();
        return getPropertiesFieldBuilder().getBuilder();
      }
      /**
       * <code>.Properties properties = 3;</code>
       */
      public TriangleOuterClass.PropertiesOrBuilder getPropertiesOrBuilder() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilder();
        } else {
          return properties_ == null ?
              TriangleOuterClass.Properties.getDefaultInstance() : properties_;
        }
      }
      /**
       * <code>.Properties properties = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TriangleOuterClass.Properties, TriangleOuterClass.Properties.Builder, TriangleOuterClass.PropertiesOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TriangleOuterClass.Properties, TriangleOuterClass.Properties.Builder, TriangleOuterClass.PropertiesOrBuilder>(
                  getProperties(),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }

      private int struct_ ;
      /**
       * <code>int32 struct = 4;</code>
       * @return The struct.
       */
      @java.lang.Override
      public int getStruct() {
        return struct_;
      }
      /**
       * <code>int32 struct = 4;</code>
       * @param value The struct to set.
       * @return This builder for chaining.
       */
      public Builder setStruct(int value) {
        
        struct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 struct = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStruct() {
        
        struct_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Triangle)
    }

    // @@protoc_insertion_point(class_scope:Triangle)
    private static final TriangleOuterClass.Triangle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TriangleOuterClass.Triangle();
    }

    public static TriangleOuterClass.Triangle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Triangle>
        PARSER = new com.google.protobuf.AbstractParser<Triangle>() {
      @java.lang.Override
      public Triangle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Triangle(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Triangle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Triangle> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TriangleOuterClass.Triangle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Properties_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Properties_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Triangle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Triangle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-protobuf-examples/vs-prost/src/triangl" +
      "e.proto\"6\n\nProperties\022\014\n\002p1\030\001 \001(\005H\000\022\014\n\002p" +
      "2\030\002 \001(\tH\000B\014\n\nproperties\"g\n\010Triangle\022\023\n\013d" +
      "escription\030\001 \001(\t\022\025\n\005color\030\002 \001(\0162\006.Color\022" +
      "\037\n\nproperties\030\003 \001(\0132\013.Properties\022\016\n\006stru" +
      "ct\030\004 \001(\005*2\n\005Color\022\013\n\007UNKNOWN\020\000\022\007\n\003RED\020\001\022" +
      "\t\n\005GREEN\020\002\022\010\n\004BLUE\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Properties_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Properties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Properties_descriptor,
        new java.lang.String[] { "P1", "P2", "Properties", });
    internal_static_Triangle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Triangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Triangle_descriptor,
        new java.lang.String[] { "Description", "Color", "Properties", "Struct", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
